#!/usr/bin/env bash

valgrind \
	--leak-check=full \
	--track-fds=yes \
	--track-origins=yes \
	--malloc-fill=0xdb \
	--free-fill=0xbd \
	--log-file=q-valgrind.log \
	--suppressions=${BASH_SOURCE[0]%/*}/valgrind.ignore \
	--gen-suppressions=all \
	--error-exitcode=234 \
	"${@}"
ret=$?
if [[ ${ret} == 234 ]] ; then
	mv q-valgrind.log q-valgrind.$$.log
	echo "valgrind log can be found at ${PWD}/q-valgrind.$$.log" >&2
	# dump complaints in Travis' log, as we cannot retrieve them lateron
	[[ -n ${RUNNER_OS} ]] && cat q-valgrind.$$.log >&2
else
	rm q-valgrind.log
fi

exit ${ret}
