.TH "QETC-UPDATE" "1" "Aug 2026" "portage-utils" "portage-utils"
.SH "NAME"
qetc\-update \- handle configuration file updates
.SH "SYNOPSIS"
.BR qetc\-update
[\fIoptions\fR] [\fI--automode <mode>\fR] [\fIpaths to scan\fR]
.SH "DESCRIPTION"
\fIqetc\-update\fR is supposed to be run after merging a new package to see if
there are updates to the configuration files.  If a new
configuration file will override an old one,
\fIqetc\-update\fR will prompt the user for a decision.
.PP
\fIqetc\-update\fR will check all directories specified on the command
line.  If no paths are given, then the \fICONFIG_PROTECT\fR variable
will be used.  All config files found in \fICONFIG_PROTECT_MASK\fR will
automatically be updated for you by \fIqetc\-update\fR.
See \fBmake.conf\fR(5) for more information.
.PP
\fIqetc\-update\fR respects the normal \fIPORTAGE_CONFIGROOT\fR and
\fIEROOT\fR variables for finding the aforementioned config protect variables.
.PP
Multiple target distributions are supported, including \fIportage\fR(5),
\fIrpm\fR(1), \fIpacman\fR(1), and \fIdpkg\fR(1) based systems.  Detection of
the target package management system is done by inspecting
\fI/etc/os\-release\fR. \fIETC_UPDATE_OS_FAMILY\fR can be used to override this
detection.
.PP
\fIqetc\-update\fR is \fBetc\-update\fR imported into portage\-utils
(it needs no installed Portage; \fBq\fR(1) supplies the configuration
values) with two behaviors from \fBdispatch\-conf\fR(1) merged in:
if the current file has not been modified by the user, as recorded in
\fI/var/lib/portage/config\fR (shared with Portage and
\fBqmerge\fR(1)), the update replaces it automatically
(\fIeu_automerge_unmodified\fR, default \fIyes\fR), and replaced
configuration files are archived with history in
\fI/etc/config\-archive\fR (\fIarchive_dir\fR).
.SH "OPTIONS"
.TP
.BR \-d ", " \-\-debug
Run with shell tracing enabled.
.TP
.BR \-h ", " \-\-help
Surprisingly, show the help output.
.TP
.BR \-p ", " \-\-preen
Automerge trivial changes only and quit.
.TP
.BR \-v ", " \-\-verbose
Show settings and important decision info while running.
.TP
.BR "\-\-automode <mode>"
Select one of the automatic merge modes.  Valid modes are: \-3 \-5 \-7 \-9.
See the \fI\-\-help\fR text for more details.
.SH "REPORTING BUGS"
Please report bugs via https://bugs.gentoo.org/
.SH "AUTHORS"
.nf
Jochem Kossen and Leo Lipelis
Karl Trygve Kalleberg <karltk@gentoo.org>
Mike Frysinger <vapier@gentoo.org>
Jaeger Hofer <antiq.hofer@gmail.com>
.fi
.SH "FILES"
.TP
.B /etc/etc\-update.conf
Configuration settings for \fIqetc\-update\fR are stored here;
\fI/etc/etc\-update.conf.d/*.conf\fR fragments are read after it.
.SH "SEE ALSO"
.BR dispatch\-conf (1),
.BR make.conf (5),
.BR qmerge (1)
