#!/bin/bash

. ../init.sh || exit 1

testit() {
	if [ -s $1 ] ; then
		tfail "$1"
		cat $1
		rm -f $1
		return
	fi
	rm -f $1
	tpass "$1"
}

prune=(
	'('
		'('
		'('
			-type d -a
			'('
				-name tests -o
				-name autotools -o
				-name autom4te.cache -o
				-name .deps -o
				-name .docker -o
				-name curl
			')'
		')'
		-o
		'('
			-type f -a
			'('
				-name '*~' -o
				-name config.h -o
				-name config.log -o
				-name config.status
			')'
		')'
		')'
		-prune
	')'
)
all_files=(
	"${prune[@]}" -o -type f
)
src_files=(
	"${prune[@]}" -o -type f -name '*.[ch]'
)



#
# check for misc common typos
#
find ${ats} "${all_files[@]}" -print0 | xargs -0 \
	grep -n -I \
		-e '\<compatability\>' \
		-e '\<compatable\>' \
		-e '\<fordeground\>' \
		-e '\<depency\>' \
		-e '\<defalt\>' \
		-e '\<remaing\>' \
		-e '\<queuing\>' \
		-e '\<detatch\>' \
		-e '\<sempahore\>' \
		-e '\<reprenstative\>' \
		-e '\<overriden\>' \
		-e '\<readed\>' \
		-e '\<formated\>' \
		-e '\<algorithic\>' \
		-e '\<deamon\>' \
		-e '\<derefernce\>' \
		-e '\<lenght\>' \
		| sed -e "s:^\.\./\.\./::g" > src.typos
testit src.typos



#
# don't allow obsolete functions or headers (portability)
#
funcs='\<(bcmp|bcopy|bzero|getwd|index|mktemp|rindex|utime)\>[[:space:]]*\('
hdrs='\<(malloc|memory|sys/(errno|fcntl|signal|stropts|termios|unistd))\.h\>'
find ${ats} "${src_files[@]}" -print0 | xargs -0 \
	grep -n -E -e "(${funcs}|${hdrs})" \
	| sed -e "s:^\.\./\.\./::g" > src.obsolete.funcs.hdrs
testit src.obsolete.funcs.hdrs



#
# every mutating qmerge/qpkg invocation in the qmerge suite must be followed
# by a check of what it actually did, not just its exit code: a merge that
# writes nothing still exits 0. add a state assertion (files, vdb, CONTENTS,
# index) or the qm_merged/qm_unmerged helpers; annotate a deliberate
# exception with "noverify".
#
awk -v FN=tests/qmerge/dotest '
BEGIN {
	st="\\$\\{ROOT\\}|var/db/pkg|qlist -I|qlist -kI|stat -c|md5sum|sha512sum|cmp -s|Packages\"|readlink|getfattr|preserved_libs_registry|wtfile|recf|vmf|REGP|tar tf|tar xOf|tar t |zstd -dc|qxpak -l|qxpak -x|tail -c|treedir|find \"|CPV:|qm_merged|qm_unmerged|noverify"
}
{ b[NR]=$0; n=NR }
END {
	for (i = 1; i <= n; i++) {
		l = b[i]
		if (l ~ /^[ \t]*(tend|#|\|\||&&|\[\[|rm |cp |mv |mkdir|printf|echo |touch)/) continue
		if (i > 1 && b[i-1] ~ /\\[ \t]*$/) continue
		if (l !~ /(^|[ \t;(|]|\$\()(qmerge|qpkg)[ \t]/) continue
		if (l ~ /-p[a-zA-Z]*[ "]|--pretend|--list-set|--info|--repos|[ \t]-s[ \t]|-ev|--deselect|--exact/) continue
		if (l !~ /(qmerge[^|]*(-F|-1|--keep-going|--no-phases|@|=)|qpkg[ \t]+-[gx])/) continue
		if (l ~ />\/dev\/null 2>&1|>\/dev\/null$/) continue
		mut[++m] = i
	}
	for (k = 1; k <= m; k++) {
		i = mut[k]
		stop = (k < m) ? mut[k+1] : n
		if (stop - i > 45) stop = i + 45
		seg = ""
		for (j = i; j < stop; j++) seg = seg " " b[j]
		if (seg !~ st) {
			cmd = b[i]
			gsub(/^[ \t]+/, "", cmd)
			printf "%s:%d: mutating command with no post-verification: %s\n", \
				FN, i, substr(cmd, 1, 80)
		}
	}
}' "${ats}/tests/qmerge/dotest" > src.unverified.merges
testit src.unverified.merges
